### ISSUE TITLE
SQL Tasks

### ISSUE THREAD

**Issue by miyconst** [Nika0429/MadeTasks#8]
## Setup

- Download and install this little software - [DB Browser for SQLite](http://sqlitebrowser.org/).
- Create a new database and execute the following SQL:

```sql
CREATE TABLE Food (Id integer NOT NULL, Name text NOT NULL, Price integer NOT NULL, Rate integer NULL, PRIMARY KEY (Id));

INSERT INTO Food (Id, Name, Price, Rate)
VALUES (1, 'Orange', 10, null),
	(2, 'Banana', 70, null),
	(3, 'Risotto', 110, null),
	(4, 'Pasta', 90, null);
```

## Write an SQL query to

- Find all food with price less than 90.
- Find all food with name equals to `Pasta`.
- Find price of the food named `Banana`.
- Insert a food with name "Steak" and price 130.
- Insert a food with rating 65.
- Insert a food with name, price, and rating.

## Difficult extra task

Write an SQL query to copy all existing food into the same table, but do the following changes:

- The price should be reduced to 90% of the original.
- The name should be updated with ` - discounted` suffix.

**Comment by Nika0429** [comment]
[Ссылка на результат](https://github.com/Nika0429/MadeTasks/blob/master/%D0%9A%D0%BE%D1%81%D1%82%D1%8F%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5SQL.md)

**Comment by miyconst** [comment]
You can use `is` operators with `NULL` value only, like `IS NULL` or `IS NOT NULL`, for string comparison the equal sign `=` should be sued.

**Comment by miyconst** [comment]
>Write an SQL query to copy all existing food into **the same table**, but do the following changes:

The difficult task is not completed. The tasks says, that you should copy the values into the same table, but you are creating a new table called `FoodNew`. So, you are copying the values into a new table.
